### ISSUE TITLE
unable to run any lwc code

### ISSUE THREAD

**Issue by Shubham1475** [divriots/webcomponents.dev#63] opened 2021-09-22 12:55 UTC
### 📖 Reproduction steps

![image](https://user-images.githubusercontent.com/55983532/134347326-2b85786b-0bcb-4c64-a4f7-fef3df411fa7.png)

### 🙁 Current Behavior

![image](https://user-images.githubusercontent.com/55983532/134347266-a64072a1-f270-45c7-b1b2-04237a282862.png)

### 🙂 Expected Behavior

any code should run without error

### 🌐 What browser(s) are you seeing the problem on?

Chrome

**Comment by jorenbroekema** [comment] 2021-09-22 13:27
Reproduced it, looking into it 👍

**Comment by gluck** [comment] 2021-09-22 22:18
Hi @Shubham1475 ,

the issue appeared since the last release (2.5) of `@lwc/compiler`, which added the support of scoped styles (https://github.com/salesforce/lwc/pull/2332).
We don't support it (yet) on the platform, so I've pinned the compiler to 2.4.0 instead of using the latest.

The fix will be deployed tomorrow, sorry for the inconvenience.

**Comment by jorenbroekema** [comment] 2021-09-29 11:04
This should be closed as we pinned the compiler to 2.4.0 and released. If it's still broken, let us know!

**Closed by jorenbroekema** 2021-09-29 11:04 UTC
Labels: bug
